name: Deploy to GitHub Pages

# Important: Before this will work on GitHub, you must:
# 1. Go to your repository -> Settings -> Actions -> General
# 2. Under "Workflow permissions" select "Read and write permissions"
# 3. Click "Save"

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Add permissions for GitHub token
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create public directory
        run: mkdir -p public

      - name: Copy source files to public directory
        run: cp -r src/* public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
